name: build-statistics-compendium
run-name: build markdown pages for /lehre/kompendium-statistik

on:
  # run when called from another workflow
  workflow_call:

  # run if user manually requests it
  workflow_dispatch:

# variables
env:

permissions:
  contents: write

jobs:
  build-pages:
    runs-on: ubuntu-latest

    steps:
      # for debugging
      - uses: crazy-max/ghaction-dump-context@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
            r-version: '4.4.1'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
          any::tidyverse
          any::scico
          any::pwr
          any::car
          any::afex
      - name: execute knit script
        working-directory: _kompendium-statistik
        run: Rscript knit-and-copy.R
